version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "nekrassov01"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    assignees:
      - "nekrassov01"
