version: "2"
linters:
  default: fast
  enable:
    - errcheck
    - gosec
    - revive
  disable:
    - cyclop
    - depguard
    - funlen
    - gocognit
    - lll
    - maintidx
    - mnd
    - nlreturn
    - testpackage
    - wsl
  exclusions:
    rules:
      - linters:
          - dupl
          - nestif
        path: '(.+)_test\.go'
      - linters:
          - revive
        text: "package-comments"
