version: 2
project_name: tlc3
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/tlc3/
    binary: tlc3
    ldflags:
      - -s -w
      - -X github.com/nekrassov01/tlc3.version={{ .Version }}
      - -X github.com/nekrassov01/tlc3.revision={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - repository:
      owner: nekrassov01
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    description: "TLS cert checker CLI"
    homepage: "https://github.com/nekrassov01/tlc3"
    license: "MIT"
    directory: Formula
release:
  use_existing_draft: true
